#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: baeldung
    password: $6$EmUjCxkffcnA4b4k$GJ1wubOVaK45NSjEzos1hvecyLvfIsnhaI6dzJOHmKnFPYHo21qoTz2yin7rOqkFxueFhZCTvZGZybSWR6Tis/
    realname: baeldung
    username: baeldung
  packages:
    - net-tools
    - p7zip-full
    - curl
  users:
    - name: root
      lock_passwd: false
      passwd: $6$gH5J/PspaMIefF29$gsCjPwy9tetZDCUyE4F9MhGp6baErOrJVOeC2aGG9n42SJ1SyRNN6jAOqbFWTS5evg5Q5UMLPrTSp3I9hyfKb/
      shell: /bin/bash
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      all-eth:
        match:
          name: "*"
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    config:
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: true
      - type: partition
        id: bios_grub_partition
        size: 1MB
        flag: bios_grub
        device: disk0
      - type: partition
        id: efi_partition
        size: 512MB
        flag: boot
        device: disk0
      - type: partition
        id: root_partition
        size: -1  # Use remaining space
        device: disk0
      - type: format
        id: efi_format
        fstype: fat32
        volume: efi_partition
      - type: format
        id: root_format
        fstype: ext4
        volume: root_partition
      - type: mount
        path: /boot/efi
        device: efi_format
      - type: mount
        path: /
        device: root_format
  updates: security
  version: 1
  late-commands:
    - |
      curtin in-target -- /bin/bash -c "IP=\$(hostname -I | awk '{print \$1}'); curl -X GET 'https://www.mydomain.com/signalCompletedInstallation.php?IP=\$IP'"
